GET http://localhost:4000/notes

###
POST http://localhost:4000/add-notes
Content-Type: application/json

{
    "title": "Tugase",
    "content": "50000",
    "category" : "tabungan"
}

###
PUT http://localhost:4000/edit-notes/3
Content-Type: application/json

{
  "title": "fotocopy",
  "content": "5k",
  "category" : "Hutang"
}

###
DELETE http://localhost:4000/delete-notes/4